New Contributor - Ananda
thenewboston-developers/Website pull request #1232
Opened 2021-01-31 06:41 UTC by Rajputusman

Added Contributor in Marketing Team with contributor ID 70

2021-01-31 16:39 UTC, thesanjeevsharma commented
@Rajputusman Can you update this PR to only add one contributor. I have created new issues for other contributors. 

Also, ID 70 is in use now. You should be using 71, 72, and 73. Confirm once, though.

2021-01-31 16:39 UTC, thesanjeevsharma commented on src/data/teams.json
> +          "contributorId": "70",
ID in use already.

2021-01-31 16:41 UTC, thesanjeevsharma requested changes
The issue has been split into 3 different issues.

2021-02-01 03:07 UTC, Rajputusman commented
@thesanjeevsharma no problem on it

2021-02-02 17:10 UTC, thesanjeevsharma approved these changes

2021-02-02 17:12 UTC, merged