1457-added contributor
thenewboston-developers/Website pull request #1459
Opened 2021-03-04 10:51 UTC by aayushi14

closes #1457

2021-03-04 18:39 UTC, thesanjeevsharma requested changes
@aayushi14 I think for this to show up on the teams page you'll have to update:
1. types/teams.ts
2. constants/teams.ts

Verify by going to the teams page once.

2021-03-05 15:35 UTC, zinoadidi commented on src/data/teams.json
> +        "label": "back-end",
label for slack is thenewboston-js

2021-03-05 15:36 UTC, zinoadidi commented
![image](https://user-images.githubusercontent.com/30411401/110137225-47264e00-7dd9-11eb-924b-487f8b4a9e23.png)
also this card could be corrected

2021-03-05 18:02 UTC, thesanjeevsharma approved these changes

2021-03-05 18:31 UTC, merged