[#1480] WIP: Add github_username and profile_image field to EditUserModal
thenewboston-developers/Website pull request #1482
Opened 2021-03-07 05:44 UTC by jamessspanggg

Fixes #1480

2021-03-07 16:12 UTC, angle943 requested changes
could you add a couple tests for the form?

1. test that display_name is required
2. test that the POST request is called with proper body

Let me know if you need help with that

2021-03-08 13:17 UTC, jamessspanggg commented
> could you add a couple tests for the form?
> 
> 1. test that display_name is required
> 2. test that the POST request is called with proper body
> 
> Let me know if you need help with that

Hmmm, I've looked up online and not too sure on how to test this in `jest`, since there's redux involved as well as post requests. Running into quite a few errors.

I might not have the time to go deep into learning and adding tests for this component. Perhaps u can decrease the # of coins for the issue and merge this first, then create another issue to add tests?

2021-03-09 06:30 UTC, angle943 commented
I'm doing a couple experiments on this branch

2021-03-11 00:41 UTC, angle943 approved these changes

2021-03-11 01:48 UTC, merged