Replaced all instances of Account Manager with Wallet
thenewboston-developers/Website pull request #1846
Opened 2021-06-11 08:13 UTC by avinashupadhya99

Closes #1843 

Account number - `94cf53921e9c5ddf48dc5589b7cdf111f7acdc93dc3073b94880416d4676b9ae`

2021-06-11 15:01 UTC, jamessspanggg commented on src/types/faq.tsx
>          id: 'where-download-account-manager',
can change the ids as well?

2021-06-11 15:02 UTC, jamessspanggg commented on src/types/faq.tsx
>          id: 'account-manager-guides',
here too

2021-06-11 16:07 UTC, avinashupadhya99 commented
@jamessspanggg do you want me to update the routes as well?

2021-06-11 23:19 UTC, angle943 commented
@avinashupadhya99 yes update the routes as well please

2021-06-11 23:30 UTC, angle943 commented
pretty much there should be absolute no mention of the Account manager in the codebase whatsoever

2021-06-11 23:31 UTC, angle943 requested changes
pretty much there should be absolute no mention of the Account manager in the codebase whatsoever

2021-06-12 04:01 UTC, avinashupadhya99 commented
I have not updated the references to the Account Manger repo since it is still named Account Manager

2021-06-12 14:19 UTC, jamessspanggg approved these changes

2021-06-12 14:21 UTC, jamessspanggg commented
Thanks for the help! Raised the bounty for ya @avinashupadhya99

2021-06-12 14:22 UTC, merged