Add beta roadmap
thenewboston-developers/Website pull request #2016
Opened 2021-08-13 12:18 UTC by jamessspanggg

Fixes #2015

2021-08-21 16:58 UTC, thesanjeevsharma commented on src/containers/Roadmap/index.tsx
> +    };
@jamessspanggg 

What if we fetch data for all the teams at once(`/roadmaps` API) and then separate it in the front-end?
I think we can avoid multiple requests to the backend.

2021-08-21 16:59 UTC, thesanjeevsharma commented on src/containers/Roadmap/index.tsx
> +    getAllRoadmaps().then((roadmapTasks) => {
let's use `async await` only.

2021-08-21 17:02 UTC, thesanjeevsharma commented on src/containers/Roadmap/index.tsx
> +  return (
Let's handle the error state too.

2021-08-21 17:06 UTC, thesanjeevsharma commented on src/components/ProgressBar/ProgressBar.scss
> +    margin-bottom: 8px;
Not an issue, but it's a good practice to avoid adding margins on components. Let the container handle it.

2021-08-21 17:10 UTC, thesanjeevsharma commented
![image](https://user-images.githubusercontent.com/29539278/130329671-a0401f9a-b87e-4196-bf85-7511da93fab4.png)

There's extra spacing on the end. It's much more on medium screen.

2021-08-21 17:16 UTC, thesanjeevsharma commented
![image](https://user-images.githubusercontent.com/29539278/130329727-422bc2d3-7b44-4fc2-800e-ac92ae29f66e.png)

There's horizontal scroll on the page. I think this is because of the `img` element in Hero section. 
btw, the way I did it was not use an `img` but put it as a background image on the `div`. 

You can ask the design team to give you the complete banner as image, so left part will be transparent and right will have the illustration. This way you'd only have to worry about the text.

This ^ solution isn't perfect at all screen sizes, but it gets the job done. It's up to you.

2021-08-21 17:20 UTC, thesanjeevsharma requested changes
Solid work 💪 @jamessspanggg 

Just some minor improvements!

2021-08-22 02:03 UTC, jamessspanggg commented
hi @thesanjeevsharma i fixed all your comments except for the hero image, will fix it once i get the image from the designer.

2021-08-22 12:17 UTC, jamessspanggg commented
Fixed all issues @thesanjeevsharma however we can only merge when @manishram updates the roadmap for other teams

2021-08-23 02:15 UTC, thesanjeevsharma approved these changes

2021-08-23 22:08 UTC, merged