Fixes: #399 Added go to top button
thenewboston-developers/Website pull request #600
Opened 2020-11-07 21:54 UTC by manishram

Fixes: #399 

1. Floating button which takes the user to the top of the page when clicked.
2. Responsive both on phone and desktop
3. Floating button only visible after user scrolls down at least 100px

Working:

![go-to-top-fix](https://user-images.githubusercontent.com/22790904/98452043-bd8baa00-2171-11eb-8ae0-4a81f52f13c6.gif)

Account: 0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

2020-11-08 10:20 UTC, thesanjeevsharma requested changes
Fix these please:

1. css needs to be alphabetical order.
2. Don't import icon directly from mdi library. Use Icon component.
3. use useEffect for adding a listener and also do a cleanup for it. check react docs.
4. I don't understand why you rendered three icon components. 🤔 
5. Remove that unnecessary div wrapper.
6. Instead for GoToTop__go-to-top use GoToTop__button
7. Remove inline styles.

2020-11-08 10:31 UTC, manishram commented
Making chnages

2020-11-08 13:58 UTC, manishram commented
@thesanjeevsharma Made changes according to the requirements.

2020-11-09 10:06 UTC, thesanjeevsharma approved these changes

2020-11-09 10:06 UTC, merged