Fixes Left Navigation Links
thenewboston-developers/Website pull request #803
Opened 2020-11-13 12:54 UTC by manishram

Fixes: #564

Converted data inside `REPOSITORIES` `OPENING_CATEGORY_FILTERS` and `TEAM_NAME_FILTERS` into objects with `title` and `url` properties.

![left](https://user-images.githubusercontent.com/22790904/99074233-635d6f80-25dd-11eb-848a-e2e36eeaeade.JPG)

2020-11-14 11:45 UTC, lapstjup commented
@manishram It would be good if @Hristijan95 reviews your changes since I guess these might be requested by him. Although instead of `any`, it would be better to create an interface for the title,url structure. Also I think - title,pathname sounds better. Confirm the same with him.

2020-11-14 11:50 UTC, Hristijan95 commented
Yep, I saw this yesterday and somehow forgot to comment. You need to create an interface instead of using any and bring back the generic <T> on the places where needed, I am not sure I understand why you changed all ComponentProps of FlatNavLinks to any. They need to be <T> & only create an new interface for the options type.
Also yeah, if it's no trouble, pathname sounds better.

2020-11-15 07:43 UTC, jamessspanggg commented on src/utils/github.ts
> +  const promises = REPOSITORIES.map((repoName: any) =>
opps, can remove the `any` here

2020-11-15 07:50 UTC, manishram commented on src/utils/github.ts
> +  const promises = REPOSITORIES.map((repoName: any) =>
done

2020-11-15 07:57 UTC, manishram commented
This PR is in collaboration with @jamessspanggg . Thankyou James!!

2020-11-15 08:26 UTC, lapstjup commented
@manishram and @jamessspanggg I have done some refactoring. The reason behind it - FlatNavLink doesn't make sense to be generic anymore since it's internal implementation depends on pathname and url fields which is obtained from NavOption.

2020-11-15 09:07 UTC, jamessspanggg requested changes

2020-11-15 09:07 UTC, jamessspanggg commented on src/containers/Teams/index.tsx
> +  {pathname: TeamName.youtube, title: 'TouTube'},
Should be `YouTube`

2020-11-15 09:13 UTC, Hristijan95 commented
Looks really nice, I'm merging it

2020-11-15 09:14 UTC, merged