Add Newsletter Modal
thenewboston-developers/Website pull request #941
Opened 2020-11-20 16:08 UTC by whitelionx

Resolves #931 
Account number: fb84a32a698a03dd327c4ce673f19fa0acf6e68cb50f143d5d7c080471bc4625

The modal is done, the only thing missing is the endpoint for saving the email in the database for the newsletter.

2020-11-20 17:29 UTC, thesanjeevsharma requested changes

2020-11-20 17:29 UTC, thesanjeevsharma commented on src/components/Footer/Footer.scss
> +    color: var(--color-white);
Alphabetical order in css - color should come first!

2020-11-20 17:29 UTC, thesanjeevsharma commented on src/components/Footer/index.tsx
> +import NewsletterForm from 'components/Newsletter/NewsletterForm';
Don't import it like this. Export and Import from components/index.js

2020-11-20 17:29 UTC, thesanjeevsharma commented on src/components/Newsletter/NewsletterForm/index.scss
> +    padding: 8px;
Alphabetical order

2020-11-20 17:29 UTC, thesanjeevsharma commented on src/components/Newsletter/NewsletterForm/index.tsx
> +import './index.scss';
Name it Newsletter.scss instead of index.scss

2020-11-20 17:29 UTC, thesanjeevsharma commented on src/components/Newsletter/NewsletterForm/index.tsx
> +        // TODO - Logic for saving the email for the upcoming newsletter
Can you complete the flow for it? Write the API calling fucntion. So, before merging I'll just replace the URL.

2020-11-20 17:29 UTC, thesanjeevsharma commented on src/components/Newsletter/NewsletterForm/index.tsx
> +      <input type="text" className="Input" placeholder="Email address" />
Make it a controlled input and add some validations to it. Use yup for validations.

2020-11-20 17:29 UTC, thesanjeevsharma commented on src/components/Newsletter/index.scss
> +  position: fixed;
Alphabetical order in this file.

2020-11-20 17:29 UTC, thesanjeevsharma commented on src/components/Newsletter/index.tsx
> +import './index.scss';
Newsletter.scss

2020-11-20 17:29 UTC, thesanjeevsharma commented on src/components/Newsletter/index.tsx
> +  const [modal, setModal] = useState(false);
Add missing type for this state

2020-11-20 18:07 UTC, whitelionx commented
Got it @thesanjeevsharma now I know what the rules are for the PR's

2020-11-20 18:39 UTC, whitelionx commented
Just to be sure do you guys want that I insert Formik into it with yup or normal form? :D @thesanjeevsharma

2020-11-20 19:54 UTC, Hristijan95 commented
@whitelionx , use Formik with yup. You can take the Formik component for input from the Account-Manager repo.

2020-11-20 20:07 UTC, whitelionx commented
Added Yup & Formik ( I used the useFormik hook as it is cleaner ), made the css alphabetical, adjusted things to be responsive, the only thing remaining is the endpoint. @thesanjeevsharma @Hristijan95

2020-11-21 12:12 UTC, whitelionx commented
Just to add to it yesterday I added an error message when the validation kicks in, I hope that's okay?

2020-11-22 16:26 UTC, lapstjup commented
Hey @whitelionx I can see the #585 PR active again. There are a lot of form components and elements that are coming from AM to Website in that PR. So once that is done, can you reuse all that is required to re-create this news letter modal ? 
I am pretty sure you will find custom Input and Modal components once that PR gets merged.

2020-11-22 18:16 UTC, whitelionx commented
This isn't a complicated form, this is just a single input field I made it as a form even though I didn't need to, so I don't see many issues keeping it this way @lapstjup but later on when all stuff gets merged it is easy to exchange the certain element for the component. No need to wait for the one or another.

2020-11-24 17:15 UTC, thesanjeevsharma commented
@whitelionx I have merged #585. You can now use Form components and elements. Can you update your PR to use those? Also, resolve these conflicts.

2020-11-24 17:25 UTC, whitelionx commented
Yeah will update it and resolve the conflicts @thesanjeevsharma

2020-12-10 22:02 UTC, buckyroberts commented
@whitelionx This PR is not needed. We are going to have GitHub auth on our website soon so no email forms needed. My mistake for not prioritizing engineering tasks as well as I could have. Paid you the task reward out of my personal funds.

2020-12-10 22:02 UTC, closed without merging